apiVersion: batch/v1
kind: Job
metadata:
  name: dq-job
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: dq
        image: dq-duckdb:1.0
        imagePullPolicy: Never
        env:
        - name: DUCK_THREADS
          value: "2"
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "2"
            memory: "1500Mi"
